// Shared registry + config generation for the Local Ingress (used by the UI
// server and deploy/seed.mjs). All paths are user-owned; the root Caddy
// daemon only READS them (--watch applies changes live).
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

export const ALIAS_IP = '127.0.49.49';
export const ALIAS_IP6 = 'fd49::4949';
export const STATE = path.join(os.homedir(), '.local/share/local-ingress');
export const SITES = path.join(STATE, 'sites');
export const CERTS = path.join(STATE, 'certs');
export const REGISTRY = path.join(STATE, 'domains.json');
export const CADDYFILE = path.join(STATE, 'Caddyfile');
export const DNS_PENDING = path.join(STATE, 'dns-pending.conf');
export const DNSMASQ_CONF = '/opt/homebrew/etc/dnsmasq.conf';
export const MKCERT = '/opt/homebrew/bin/mkcert';

export const ensureDirs = () => {
	for (const dir of [STATE, SITES, CERTS]) fs.mkdirSync(dir, { recursive: true });
};

export const readRegistry = () => {
	try {
		return JSON.parse(fs.readFileSync(REGISTRY, 'utf8'));
	} catch {
		return { domains: [] };
	}
};

export const writeRegistry = (reg) => fs.writeFileSync(REGISTRY, JSON.stringify(reg, null, '\t') + '\n');

const siteBlock = ({ host, port }) => `# Generated by local-ingress — do not hand-edit (the registry wins).
https://${host} {
	bind ${ALIAS_IP} ${ALIAS_IP6}
	tls ${CERTS}/${host}.pem ${CERTS}/${host}-key.pem
	reverse_proxy 127.0.0.1:${port}
}

http://${host} {
	bind ${ALIAS_IP} ${ALIAS_IP6}
	redir https://${host}{uri} 308
}
`;

export const dnsLines = (host) => [`address=/${host}/${ALIAS_IP}`, `address=/${host}/${ALIAS_IP6}`];

// /etc/hosts entries too: Chrome's Secure DNS (DoH) bypasses scoped
// resolvers AND dnsmasq — .test is guaranteed-NXDOMAIN at any public
// resolver — but every browser still consults the hosts file first.
export const HOSTS_FILE = '/etc/hosts';
export const HOSTS_PENDING = path.join(STATE, 'hosts-pending.conf');
export const hostsLines = (host) => [`${ALIAS_IP} ${host}`, `${ALIAS_IP6} ${host}`];

// Privileged residue (dnsmasq address= lines + /etc/hosts entries) is
// staged into pending files and applied by deploy/apply-dns.sh. A line
// leaves its staging file once the target file already carries it.
export const refreshDnsPending = () => {
	const conf = fs.existsSync(DNSMASQ_CONF) ? fs.readFileSync(DNSMASQ_CONF, 'utf8') : '';
	const hosts = fs.existsSync(HOSTS_FILE) ? fs.readFileSync(HOSTS_FILE, 'utf8') : '';
	const reg = readRegistry();
	const pendingDns = reg.domains.flatMap((d) => dnsLines(d.host)).filter((line) => !conf.includes(line));
	const pendingHosts = reg.domains.flatMap((d) => hostsLines(d.host)).filter((line) => !hosts.includes(line));
	fs.writeFileSync(DNS_PENDING, pendingDns.length ? pendingDns.join('\n') + '\n' : '');
	fs.writeFileSync(HOSTS_PENDING, pendingHosts.length ? pendingHosts.join('\n') + '\n' : '');
	return [...pendingDns, ...pendingHosts];
};

// caddy --watch watches the MAIN config file; imported site files are
// re-read on reload, so bumping the generation comment triggers the reload.
export const regenerate = () => {
	ensureDirs();
	const reg = readRegistry();
	for (const f of fs.readdirSync(SITES)) {
		if (f.endsWith('.caddy')) fs.rmSync(path.join(SITES, f));
	}
	for (const d of reg.domains) {
		fs.writeFileSync(path.join(SITES, `${d.host}.caddy`), siteBlock(d));
	}
	fs.writeFileSync(
		CADDYFILE,
		`# Local Ingress root config (am.danielk.local-ingress runs this with --watch).\n# generation: ${Date.now()}\n{\n\tadmin off\n\tauto_https off\n}\n\nimport ${SITES}/*.caddy\n`
	);
	refreshDnsPending();
};
